openapi: 3.0.0
info:
  title: Employee Management API
  description: API for managing employee information
  version: 1.0.0
servers:
  - url: http://localhost:8080/skeleton/v1
paths:
  /employees:
    get:
      summary: Get a list of employees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
  /employees/{employeeId}:
    parameters:
      - name: employeeId
        in: path
        required: true
        description: ID of the employee to update
        schema:
          type: integer
          format: int64
    put:
      summary: Update an employee by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: Employee updated successfully
        '404':
          description: Employee not found
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          pattern: '^[a-zA-Z ]+$'
        department:
          type: string
          enum:
            - IT
            - FINANCE
        position:
          type: string
        salary:
          type: number
          format: double
          minimum: 0
          multipleOf: 0.01
